server:
  port: 8081
  servlet:
    context-path: /  #该配置可以删除,默认配置就是" / "
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zljx_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#配置mybatis-plus
mybatis-plus:
  type-aliases-package: com.manage.pojo
  mapper-locations: classpath:/mappers/*.xml
  #开启驼峰映射
  configuration:
   map-underscore-to-camel-case: true
  
  